# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-01 20:44
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Preferences',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Your name')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('geom', django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='WeatherDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_name', models.CharField(max_length=30, null=True)),
                ('lat', models.DecimalField(decimal_places=6, max_digits=9, null=True)),
                ('long', models.DecimalField(decimal_places=6, max_digits=9, null=True)),
                ('clo', models.IntegerField(null=True)),
                ('temp', models.IntegerField(null=True)),
                ('temp_min', models.IntegerField(null=True)),
                ('temp_max', models.IntegerField(null=True)),
                ('pressure', models.IntegerField(null=True)),
                ('humidity', models.IntegerField(null=True)),
                ('weather_details', models.CharField(max_length=40, null=True)),
                ('description', models.CharField(max_length=100, null=True)),
                ('wind_speed', models.FloatField(null=True)),
                ('wind_degrees', models.FloatField(null=True)),
                ('date_time', models.IntegerField(null=True)),
            ],
        ),
    ]
